# Generated by Django 4.0.3 on 2024-01-23 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_No', models.CharField(blank=True, max_length=250)),
                ('Card_Name', models.CharField(blank=True, max_length=250, null=True)),
                ('User_Name', models.CharField(blank=True, max_length=250, null=True)),
                ('Email_Id', models.CharField(blank=True, max_length=250, null=True)),
                ('Company_Name', models.CharField(blank=True, max_length=250, null=True)),
                ('Designation_Name', models.CharField(blank=True, max_length=250, null=True)),
                ('Address', models.CharField(blank=True, max_length=250, null=True)),
                ('Website_url', models.CharField(blank=True, max_length=250, null=True)),
                ('Linkdin_url', models.CharField(blank=True, max_length=250, null=True)),
                ('Notes', models.TextField(blank=True, null=True)),
                ('Tags', models.TextField(blank=True, null=True)),
                ('Profile_pic', models.CharField(blank=True, max_length=250, null=True)),
                ('Priority', models.CharField(blank=True, max_length=250, null=True)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
                ('User_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.users')),
            ],
        ),
    ]
