# Generated by Django 4.0.3 on 2024-01-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='Country_Code',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='Address',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='Card_Name',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='Company_Name',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='Designation_Name',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='Email_Id',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='Linkdin_url',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='Notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='Priority',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='Profile_pic',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='Tags',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='User_Name',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='Website_url',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
