# Generated by Django 4.0.3 on 2024-02-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0003_contacts_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, unique=True)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='contacts',
            name='Favorite',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='Tags',
        ),
        migrations.AddField(
            model_name='contacts',
            name='Tags',
            field=models.ManyToManyField(to='Contacts.tag'),
        ),
    ]
