# Generated by Django 4.0.3 on 2024-02-02 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0004_tag_contacts_favorite_remove_contacts_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Messages', models.TextField()),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
                ('Contact_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contacts.contacts')),
            ],
        ),
    ]
