# Generated by Django 4.0.3 on 2024-02-02 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0005_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='Notes',
        ),
    ]
