# Generated by Django 4.0.3 on 2024-02-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0006_remove_contacts_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Remarks',
        ),
        migrations.AddField(
            model_name='contacts',
            name='Notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
