# Generated by Django 4.0.3 on 2024-01-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='OTP',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
