# Generated by Django 4.0.3 on 2024-01-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_users_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Country_Code',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='users',
            name='Address',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='users',
            name='Company_Name',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='users',
            name='Designation_Name',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='users',
            name='Email_Id',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='users',
            name='Linkdin_url',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='users',
            name='Notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='users',
            name='OTP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='Profile_pic',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='users',
            name='User_Name',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='users',
            name='Website_url',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
